{
  "resorts": [
    {
      "resortName": "Gran Hotel Manzana Kempinski La Habana",
      "location": "Calle San Rafael, Old Havana, Havana, Cuba (Plaza Central, Historic Center)",
      "images": [
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/9/2/9/8/548929-1-eng-GB/Gran-Hotel-Manzana-Kempinski-La-Habana-Hotel-Exterior.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/5/7/7/1/561775-1-eng-GB/Gran-Deluxe-Room-Bedroom.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/4/9/5/8/558594-1-eng-GB/Rooftop-Pool.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/8/2/8/1/551828-1-eng-GB/San-Cristobal-Restaurant.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/2/8/9/8/558982-1-eng-GB/Spa-Albear-Treatment-Room.jpg"
      ],
      "resortDescription": "Gran Hotel Manzana Kempinski La Habana is Cuba's first true luxury hotel, occupying the historic Manzana de Gómez building that was originally constructed between 1894 and 1917 as Cuba's first European-style shopping arcade. This magnificent 5-star property sits in the heart of Old Havana's UNESCO World Heritage district, directly facing the National Capitol and Gran Teatro de La Habana. The hotel features 246 elegantly appointed rooms and suites spread across seven floors, with the building retaining its iconic whitewashed neoclassical façade while housing thoroughly modern interiors. The property showcases ground-floor luxury retail including Versace, Giorgio Armani, Lacoste, and Montblanc, honoring the building's original commercial heritage. Guests enjoy a spectacular rooftop pool and bar offering 360-degree panoramic views of Old Havana's colonial architecture and surrounding cityscape, the refined Spa Albear by Resense, two gourmet restaurants including San Cristobal with breathtaking city vistas, an elegant Cigar Bar, sophisticated Lobby Bar, fully equipped fitness center, and multiple event spaces. Operated by Europe's oldest luxury hotel group Kempinski, this landmark property combines rich Cuban heritage with European luxury standards and impeccable personalized service.",
      "roomDescription": "Gran Hotel Manzana Kempinski offers 219 rooms and 27 suites featuring contemporary luxury with Cuban elegance. Room categories include Patio Rooms (38 sqm) with tranquil inner courtyard views, Deluxe Rooms (38 sqm) with vibrant Old Havana city views, and Gran Deluxe Rooms (55 sqm) with spacious layouts and historic city panoramas. All accommodations feature king or queen beds with premium linens, floor-to-ceiling windows with blackout curtains, marble bathrooms with walk-in rain showers, designer Philippe Starck fixtures, luxury bath amenities, separate soaking tubs in larger categories, air conditioning with individual climate control, flat-screen satellite TVs, Nespresso machines, well-stocked minibars, electronic safes, premium WiFi, and elegant décor combining classic Cuban style with modern sophistication through gleaming chandeliers, rich fabrics, and polished wood furnishings. Select rooms and suites feature private balconies overlooking the bustling streets of Havana. Suites provide enhanced space with separate living areas, upgraded amenities, butler service, and spectacular views. The contemporary design emphasizes comfort and refined elegance, creating serene urban sanctuaries."
    },
    {
      "resortName": "Iberostar Grand Packard",
      "location": "Calle Prado No. 51, Paseo del Prado, Old Havana, Havana, Cuba",
      "images": [
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-grand-packard-fachada.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-grand-packard-habitacion.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-grand-packard-piscina.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-grand-packard-spa.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-grand-packard-restaurante.jpg"
      ],
      "resortDescription": "Iberostar Grand Packard is a spectacular 5-star luxury hotel on Havana's iconic Paseo del Prado, positioned perfectly between Old Havana's Parque Central and the famous Malecón seafront promenade. Named after the legendary luxury automobile, this modernist property rose phoenix-like from the ruins of the original century-old Packard Hotel, representing a near-complete reconstruction that honors colonial heritage while delivering cutting-edge 21st-century luxury. The hotel features 321 rooms and suites across multiple categories, crowned by a stunning sixth-floor infinity pool offering unparalleled panoramic views of the Malecón, Havana Bay, El Morro fortress, and the Atlantic Ocean. The property boasts five exceptional restaurants including gourmet Biscuit serving Creole-Spanish fusion, traditional Tradiciones showcasing authentic Cuban cuisine, a Spanish tapas bar, international Clipper restaurant, and an exclusive Executive Breakfast lounge for Cosmos Level guests. Additional amenities include the luxurious SPA Sensations, three sophisticated bars including a distinguished Cigar Lounge, state-of-the-art fitness center with group classes, business center accommodating up to 350 people, exclusive Cosmos Level access with premium rooms and services, 24-hour concierge, butler service for suites, and evening entertainment featuring live Cuban music and dance performances. The hotel's prime location places guests steps from the Capitol, Museum of the Revolution, and all major Old Havana attractions.",
      "roomDescription": "Iberostar Grand Packard offers elegantly appointed rooms and suites across multiple categories including Deluxe Rooms, Deluxe Prado with city avenue views, Deluxe Atlantic with Malecón sea views, spacious Deluxe Premium rooms with breakfast areas and sofas, and luxurious Deluxe Premium Prado with panoramic Paseo del Prado vistas. All accommodations feature plush king or queen beds with premium linens, individually controlled air conditioning, modern marble bathrooms with walk-in rainfall showers and premium amenities, flat-screen satellite TVs, minibars with refreshments, electronic safes, hair dryers, irons with ironing boards, complimentary WiFi throughout, and 24-hour room service. Many rooms include private balconies or Juliet balconies offering views of the vibrant Paseo del Prado, the vertical garden, the historic cityscape, or the shimmering Atlantic Ocean and Malecón. The sophisticated design blends contemporary elegance with art deco influences, featuring rich wood tones, elegant furnishings, modern artwork, and refined color palettes creating bright, spacious, and exceptionally comfortable retreats. Suites provide additional living space, enhanced amenities, priority reservations, and personalized butler service."
    },
    {
      "resortName": "Meliá Cohiba",
      "location": "Paseo, between 1st and 3rd, Vedado, Havana, Cuba",
      "images": [
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-cohiba/rooms/melia-cohiba-the-level-room.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-cohiba/hotel/melia-cohiba-exterior.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-cohiba/hotel/melia-cohiba-pool.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-cohiba/restaurants/melia-cohiba-restaurant.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-cohiba/services/melia-cohiba-spa.jpg"
      ],
      "resortDescription": "Meliá Cohiba is a premium 5-star hotel in Havana's modern Vedado district, standing prominently along the famous Malecón seafront boulevard with breathtaking ocean views. This sophisticated high-rise property is ideally positioned near the National Theater, Anti-Imperialist Tribune, and just minutes from Old Havana's historic attractions. The hotel features 462 elegantly designed rooms and suites including exclusive Executive Level accommodations with enhanced amenities and dedicated services. Meliá Cohiba offers multiple dining venues serving international and Cuban cuisine, stylish bars including a legendary piano bar, outdoor swimming pool overlooking the Malecón, modern fitness center, business facilities, spa and wellness center, shopping arcade, car rental services, and comprehensive concierge assistance. The property caters to both leisure and business travelers with extensive meeting spaces and professional event coordination. The Executive Level provides access to an exclusive lounge with complimentary breakfast, afternoon snacks, premium beverages, personalized check-in/out, and enhanced in-room amenities, making it perfect for discerning travelers seeking elevated experiences in Cuba's vibrant capital.",
      "roomDescription": "Meliá Cohiba offers spacious rooms and suites with modern design and comprehensive amenities. Executive Level rooms provide enhanced comfort with king or queen beds featuring premium linens, contemporary furnishings, marble bathrooms with bathtubs and rainfall showers, luxury toiletries, bathrobes and slippers, air conditioning, flat-screen TVs with international channels, minibars stocked with beverages, coffee/tea facilities, electronic safes, work desks with ergonomic chairs, complimentary high-speed WiFi, and many rooms featuring private balconies with spectacular Malecón and ocean views. Executive Level guests receive exclusive access to the private lounge offering complimentary breakfast buffet, evening cocktails and canapés, business services, and personalized concierge attention. Room décor emphasizes clean lines, warm neutral tones, elegant wood accents, and contemporary artwork creating sophisticated urban retreats. Suites provide additional living space with separate seating areas, dining tables, upgraded amenities, and panoramic city or sea views."
    },
    {
      "resortName": "Meliá Habana",
      "location": "3ra Avenue between 76 and 80, Miramar, Playa, Havana, Cuba",
      "images": [
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-habana/rooms/melia-habana-premium-room.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-habana/hotel/melia-habana-exterior-night.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-habana/hotel/melia-habana-pool-area.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-habana/restaurants/melia-habana-buffet-restaurant.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/havana/melia-habana/services/melia-habana-business-center.jpg"
      ],
      "resortDescription": "Meliá Habana is a modern 5-star business and leisure hotel in Havana's upscale Miramar residential and diplomatic district, offering a quieter alternative to downtown while remaining easily accessible to Old Havana and major business centers. This contemporary property features 397 spacious rooms and suites set within beautifully landscaped tropical gardens. The hotel emphasizes business facilities with extensive meeting rooms, convention spaces, business center with secretarial services, and professional event planning. Leisure amenities include a large outdoor swimming pool surrounded by lush gardens, poolside bar service, modern fitness center, tennis courts, YHI Spa offering massage and wellness treatments, multiple restaurants serving international buffets and à la carte specialties, elegant bars and lounges, shopping arcade, car rental desk, and attentive concierge services. The property is particularly popular with business travelers, diplomatic guests, and those seeking a more residential neighborhood atmosphere while visiting Havana. Its location near embassies, international businesses, and the Miramar Trade Center makes it ideal for corporate stays while still providing easy access to cultural attractions.",
      "roomDescription": "Meliá Habana features contemporary rooms and suites with modern comfort and business-friendly amenities. Accommodations include comfortable king or queen beds with quality linens, spacious marble bathrooms with bathtubs and showers, premium bath products, plush bathrobes and slippers, individually controlled air conditioning, flat-screen satellite TVs, well-stocked minibars, coffee and tea making facilities, electronic safes, spacious work desks with ergonomic seating, complimentary high-speed WiFi, direct-dial telephones with voicemail, and most rooms featuring private balconies overlooking tropical gardens or the city. Premium and executive categories offer enhanced space, upgraded amenities, and access to exclusive services. The contemporary design uses neutral color palettes, elegant furnishings, modern artwork, and floor-to-ceiling windows providing abundant natural light. Rooms are designed for both relaxation and productivity, featuring separate work areas perfect for business travelers while maintaining comfortable atmospheres for leisure guests."
    },
    {
      "resortName": "Royalton Hicacos Resort & Spa",
      "location": "Carretera Las Morlas, Varadero, Matanzas, Cuba",
      "images": [
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/varadero/royalton-hicacos/images/royalton-hicacos-resort-aerial.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/varadero/royalton-hicacos/images/royalton-hicacos-junior-suite.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/varadero/royalton-hicacos/images/royalton-hicacos-pool.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/varadero/royalton-hicacos/images/royalton-hicacos-beach.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/varadero/royalton-hicacos/images/royalton-hicacos-restaurant.jpg"
      ],
      "resortDescription": "Royalton Hicacos Resort & Spa is an exclusive adults-only, all-inclusive luxury resort on Varadero's stunning Hicacos Peninsula, offering direct access to pristine white-sand beaches and crystal-clear turquoise Caribbean waters. This sophisticated property features modern architecture set within tropical gardens, providing an elegant atmosphere perfect for couples, honeymooners, and adult travelers seeking tranquil beachfront relaxation. The resort boasts multiple specialty restaurants including Italian, Asian fusion, international buffet, and gourmet à la carte options, numerous bars serving premium spirits and creative cocktails, multiple swimming pools including an infinity pool, private beach with loungers and palapas, Royal Spa featuring hydrotherapy circuits and comprehensive treatments, state-of-the-art fitness center, non-motorized water sports, evening entertainment with live music and shows, casino, sports facilities including tennis and beach volleyball, and Diamond Club upgrades offering premium accommodations with exclusive access to private pool areas, upgraded amenities, and enhanced services. The all-inclusive concept includes unlimited food and beverages from top-shelf brands, 24-hour room service, daily activities, and nightly entertainment.",
      "roomDescription": "Royalton Hicacos features spacious junior suites and suites designed for adult luxury and comfort. All accommodations include king or double beds with luxury linens and pillow menus, modern furnishings with elegant Caribbean-inspired décor, marble bathrooms with rainfall showers, whirlpool tubs in many categories, premium bath amenities including bathrobes and slippers, air conditioning, flat-screen TVs with satellite channels, stocked minibars replenished daily with beverages and snacks, coffee makers with Lavazza coffee, electronic safes, irons with boards, hair dryers, complimentary WiFi, and furnished balconies or terraces with garden, pool, or ocean views. Diamond Club suites provide enhanced luxury with priority reservations, exclusive pool and beach areas, premium room locations, upgraded minibar selection, enhanced bathroom amenities, and personalized concierge services. The contemporary design emphasizes relaxation with soothing color palettes, modern artwork, quality furnishings, and thoughtful details creating romantic adults-only retreats perfect for couples."
    },
    {
      "resortName": "Paradisus Varadero",
      "location": "Punta Francés, Varadero, Matanzas, Cuba",
      "images": [
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-varadero/hotel/paradisus-varadero-aerial-view.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-varadero/rooms/paradisus-varadero-royal-service-junior-suite.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-varadero/hotel/paradisus-varadero-pools.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-varadero/hotel/paradisus-varadero-beach.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-varadero/restaurants/paradisus-varadero-restaurant.jpg"
      ],
      "resortDescription": "Paradisus Varadero is a premium 5-star all-inclusive resort on Varadero's exclusive Punta Francés, featuring 2 kilometers of spectacular private beach with powder-white sand and crystalline Caribbean waters. This luxurious property showcases expansive tropical gardens with native vegetation, creating an oasis atmosphere. The resort offers The Reserve concept with adults-only accommodations, Royal Service for enhanced luxury with exclusive amenities, and Family Concierge for family-friendly experiences. Guests enjoy 11 specialty restaurants including Italian, Japanese teppanyaki, seafood, steakhouse, Mediterranean, and Cuban cuisine, 13 bars serving premium beverages, multiple swimming pools including adults-only and family pools, YHI Spa with comprehensive wellness treatments and hydrotherapy, extensive water sports center, fitness facilities, tennis courts, organized activities and entertainment programs, kids' club and teen's club, nightly shows and live music, and convention facilities for events and weddings. The all-inclusive experience includes gourmet dining without reservations, top-shelf spirits, 24-hour room service, water sports, entertainment, and personalized services creating worry-free vacations.",
      "roomDescription": "Paradisus Varadero features spacious junior suites and suites across multiple categories. Standard accommodations include Garden View and Ocean View junior suites with king or two queen beds, contemporary tropical décor, marble bathrooms with hydromassage bathtubs and separate showers, luxury amenities, air conditioning, flat-screen satellite TVs, stocked minibars, coffee facilities, electronic safes, and furnished terraces or balconies. Royal Service suites provide elevated luxury with exclusive access to the Royal Service infinity pool and lounge, priority restaurant reservations, premium liquors in minibar, pillow menus, bathrobes and slippers, upgraded bath products, butler service, express check-in/out, and enhanced room amenities. Family Concierge offers family-focused services with connecting rooms, kids' welcome packages, special children's amenities, and dedicated concierge assistance. The Reserve section features adults-only accommodations with contemporary design, private pools, exclusive dining venues, and serene atmospheres perfect for couples."
    },
    {
      "resortName": "Paradisus Princesa del Mar",
      "location": "Punta Francés, Varadero, Matanzas, Cuba",
      "images": [
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-princesa-del-mar/hotel/paradisus-princesa-resort-view.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-princesa-del-mar/rooms/paradisus-princesa-suite-terrace.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-princesa-del-mar/hotel/paradisus-princesa-pool.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-princesa-del-mar/hotel/paradisus-princesa-beach.jpg",
        "https://www.melia.com/content/dam/paradisus/cuba/varadero/paradisus-princesa-del-mar/restaurants/paradisus-princesa-dining.jpg"
      ],
      "resortDescription": "Paradisus Princesa del Mar is an exclusive adults-only, all-inclusive luxury resort in Varadero, sharing the pristine Punta Francés beachfront with its sister property Paradisus Varadero while maintaining its own intimate atmosphere tailored for couples and adult travelers. This sophisticated resort emphasizes tranquility and romance with elegant colonial-style architecture surrounded by lush tropical gardens and direct access to spectacular white-sand beaches. The property features Royal Service accommodations with premium amenities and services, multiple gourmet specialty restaurants offering diverse international cuisines, elegant bars and lounges, multiple swimming pools including infinity pools with ocean views, YHI Spa providing comprehensive wellness treatments and hydrotherapy circuits, fitness center, water sports facilities, tennis courts, evening entertainment with live shows and music, and personalized concierge services. The adults-only environment creates peaceful atmospheres ideal for romantic getaways, honeymoons, and couples seeking relaxation without children. Guests can access facilities at the adjacent Paradisus Varadero, effectively doubling dining and entertainment options while maintaining the serene adults-only sanctuary.",
      "roomDescription": "Paradisus Princesa del Mar offers spacious junior suites and suites designed exclusively for adults, featuring elegant colonial-inspired décor with contemporary comfort. All accommodations include king-size beds with luxury linens and pillow menus, sophisticated furnishings with romantic touches, marble bathrooms featuring hydromassage bathtubs and separate rainfall showers, premium bath amenities including bathrobes and slippers, individually controlled air conditioning, flat-screen satellite TVs, well-stocked minibars replenished daily with premium beverages and snacks, Nespresso coffee makers, electronic safes, hair dryers, irons with boards, complimentary high-speed WiFi, and private furnished terraces or balconies with views of tropical gardens or the ocean. Royal Service suites provide enhanced luxury including exclusive access to Royal Service lounge and infinity pool, priority restaurant reservations, butler service available upon request, upgraded minibar selections with premium spirits, enhanced turndown service, and personalized attention. The sophisticated design emphasizes romance and tranquility with soft lighting, elegant color schemes, quality furnishings, and intimate details creating perfect couples' retreats."
    },
    {
      "resortName": "Iberostar Selection Varadero",
      "location": "Carretera Las Morlas Km 15, Varadero, Matanzas, Cuba",
      "images": [
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-selection-varadero-exterior.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-selection-varadero-room.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-selection-varadero-pool.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-selection-varadero-beach.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-selection-varadero-restaurant.jpg"
      ],
      "resortDescription": "Iberostar Selection Varadero is a comprehensive all-inclusive beachfront resort on Varadero's stunning coastline, offering direct access to pristine white-sand beaches and turquoise Caribbean waters. This family-friendly property features contemporary architecture set within extensive tropical gardens, providing diverse accommodation options and amenities suitable for families, couples, and groups. The resort boasts multiple specialty restaurants serving Cuban, international, Italian, Asian, and gourmet cuisine, numerous bars including swim-up pool bars and beach bars, several swimming pools including children's pools and activity pools, Star Camp kids' club with supervised activities and facilities, teen lounge, extensive water sports center offering kayaking, snorkeling, and sailing, fitness center with modern equipment, organized entertainment programs throughout the day, nightly shows and live music, spa services and wellness treatments, sports facilities including tennis, beach volleyball, and mini-golf, and comprehensive wedding and event services. The Star Prestige section offers upgraded accommodations with exclusive areas, private check-in, premium services, and enhanced amenities for guests seeking elevated experiences within this vibrant resort environment.",
      "roomDescription": "Iberostar Selection Varadero features comfortable rooms and junior suites with contemporary tropical design. Standard accommodations include king or two double beds with quality linens, modern furnishings with bright Caribbean-inspired colors, bathrooms with showers or bathtub/shower combinations, amenity kits, air conditioning, flat-screen satellite TVs, stocked minibars replenished daily, coffee/tea facilities, electronic safes, hair dryers, irons, complimentary WiFi, and furnished balconies or terraces with garden, pool, or ocean views. Star Prestige rooms provide enhanced comfort with exclusive access to Star Prestige lounge offering complimentary beverages and snacks, premium room locations often with ocean views, upgraded bathroom amenities including bathrobes and slippers, pillow menus, priority restaurant reservations, enhanced turndown service, and personalized concierge attention. Family rooms offer additional space with separate sleeping areas or connecting options. The design emphasizes bright, cheerful atmospheres with contemporary comfort and practical layouts suitable for family vacations and couple getaways."
    },
    {
      "resortName": "Blau Varadero",
      "location": "Carretera Las Morlas Km 14.5, Varadero, Matanzas, Cuba",
      "images": [
        "https://www.bluebayresorts.com/content/dam/blau/cuba/varadero/blau-varadero/images/blau-varadero-aerial-beach.jpg",
        "https://www.bluebayresorts.com/content/dam/blau/cuba/varadero/blau-varadero/images/blau-varadero-adults-suite.jpg",
        "https://www.bluebayresorts.com/content/dam/blau/cuba/varadero/blau-varadero/images/blau-varadero-infinity-pool.jpg",
        "https://www.bluebayresorts.com/content/dam/blau/cuba/varadero/blau-varadero/images/blau-varadero-beachfront.jpg",
        "https://www.bluebayresorts.com/content/dam/blau/cuba/varadero/blau-varadero/images/blau-varadero-gourmet-dining.jpg"
      ],
      "resortDescription": "Blau Varadero is an exclusive adults-only, all-inclusive luxury resort on Varadero Beach, designed specifically for couples and adult travelers seeking sophisticated beachfront experiences. This upscale property features contemporary architecture with Mediterranean influences, offering direct access to pristine white-sand beaches and crystalline Caribbean waters. The adults-only concept creates tranquil, romantic atmospheres throughout the property. The resort boasts multiple gourmet specialty restaurants including Italian, Asian fusion, seafood, steakhouse, and international buffet options, elegant bars and lounges serving premium beverages, multiple swimming pools including stunning infinity pools with ocean views, swim-up pool bars, private beach areas with Bali beds and personal butler service, Privilege Club accommodations with exclusive amenities, comprehensive spa center offering therapeutic massages and beauty treatments, modern fitness facilities, water sports including snorkeling and kayaking, tennis courts, evening entertainment with live music and shows, and personalized concierge services. The all-inclusive premium experience includes unlimited gourmet dining, top-shelf spirits, 24-hour room service for Privilege guests, and romantic turndown service, making it ideal for honeymoons, anniversaries, and romantic getaways.",
      "roomDescription": "Blau Varadero features spacious junior suites and suites exclusively for adults, emphasizing romantic design and comfort. All accommodations include king-size beds with luxury linens and pillow menus, contemporary Mediterranean-inspired décor, elegant bathrooms with whirlpool tubs and separate rainfall showers, premium bath amenities with bathrobes and slippers, air conditioning, flat-screen TVs with satellite channels, well-stocked minibars replenished daily with premium beverages, coffee makers with quality coffee, electronic safes, complimentary WiFi, and furnished balconies or terraces offering garden, pool, or spectacular ocean views. Privilege Club suites provide elevated luxury with exclusive access to Privilege Lounge offering gourmet snacks and premium beverages throughout the day, private pool area, priority restaurant reservations, butler service, enhanced minibar selections, upgraded bath products, welcome amenities, and personalized concierge attention. The sophisticated design uses soothing color palettes, elegant furnishings, romantic lighting, and quality materials creating intimate couple-oriented retreats perfect for celebrating special occasions or simply enjoying luxurious beach vacations together."
    },
    {
      "resortName": "Cayo Guillermo Resort Kempinski",
      "location": "Cayo Guillermo, Morón, Ciego de Ávila, Cuba",
      "images": [
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/cayo-guillermo-resort-exterior.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/cayo-guillermo-junior-suite-ocean.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/cayo-guillermo-infinity-pool.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/cayo-guillermo-beach-view.jpg",
        "https://www.kempinski.com/var/site/storage/images/_aliases/header_full/cayo-guillermo-restaurant-terrace.jpg"
      ],
      "resortDescription": "Cayo Guillermo Resort Kempinski is a 5-star all-inclusive luxury resort on the pristine island of Cayo Guillermo, featuring 5 kilometers of spectacular white-sand beaches and protected coral reefs perfect for snorkeling. This European luxury property by Kempinski Hotels brings sophisticated service to Cuba's northern cays, offering an exclusive island paradise experience. The resort features 245 elegant rooms and suites with colonial-Caribbean architecture, five specialty restaurants serving international gourmet cuisine including Italian, Asian, seafood, steakhouse, and Cuban specialties, multiple bars and lounges, three swimming pools including an adults-only infinity pool, direct beach access with water sports facilities, Resense Spa offering comprehensive wellness treatments, fitness center, tennis courts, kids' club and teen programs, nightly entertainment with live shows, water sports including sailing and windsurfing, diving center with PADI certification courses, and personalized concierge services. The all-inclusive concept includes premium beverages, gourmet dining, water sports, and activities. The remote island location provides tranquility and natural beauty away from mass tourism, accessible via scenic causeway from mainland Cuba.",
      "roomDescription": "Cayo Guillermo Resort Kempinski offers elegantly appointed junior suites and suites with colonial-Caribbean design and European luxury standards. All accommodations feature king or two double beds with premium linens, spacious layouts averaging 50-65 sqm, marble bathrooms with rainfall showers and whirlpool tubs, luxury Molton Brown bath amenities, plush bathrobes and slippers, individually controlled air conditioning, flat-screen satellite TVs, Nespresso coffee machines, well-stocked minibars replenished daily, electronic safes, hair dryers, irons with boards, complimentary WiFi, and furnished terraces or balconies with tropical garden or ocean views. Ocean View and Beachfront suites provide direct beach access or spectacular sea vistas. The décor combines white-washed walls, rich mahogany furnishings, Caribbean blue accents, elegant fabrics, and colonial-inspired details creating sophisticated tropical elegance. Suites offer additional space with separate living areas, upgraded amenities, and enhanced services. The design emphasizes natural light, comfort, and seamless indoor-outdoor living perfect for island relaxation."
    },
    {
      "resortName": "Iberostar Selection Playa Pilar",
      "location": "Cayo Guillermo, Morón, Ciego de Ávila, Cuba",
      "images": [
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-playa-pilar-beach.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-playa-pilar-room.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-playa-pilar-pool.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-playa-pilar-dining.jpg",
        "https://www.ibercuba.com/cdn-cgi/image/format=webp,quality=75/uploads/iberostar-playa-pilar-spa.jpg"
      ],
      "resortDescription": "Iberostar Selection Playa Pilar is a premium all-inclusive resort on Cayo Guillermo, adjacent to the famous Playa Pilar beach consistently ranked among the Caribbean's most beautiful beaches. This family-friendly property offers direct access to pristine white-sand beaches with shallow turquoise waters perfect for swimming and water sports. The resort features contemporary tropical architecture within lush gardens, creating a relaxed island atmosphere. Amenities include multiple specialty restaurants serving Cuban, Italian, Asian, Mediterranean, and international cuisine, several bars including beach and pool bars, multiple swimming pools with children's areas, Star Camp kids' club with supervised activities, teen lounge, extensive water sports center, diving facilities with coral reef access, SPA Sensations wellness center, fitness facilities, tennis courts, organized daily activities and entertainment, nightly shows with live music, sports programs, and Star Prestige accommodations with exclusive services. The island location provides natural beauty, protected marine environments ideal for snorkeling, and tranquil atmospheres away from mainland crowds while offering comprehensive resort amenities and services.",
      "roomDescription": "Iberostar Selection Playa Pilar offers comfortable rooms and junior suites with tropical contemporary design. Standard accommodations include king or two double beds with quality linens, modern bathrooms with showers or tub/shower combinations, amenities, air conditioning, flat-screen TVs, minibars replenished daily, coffee facilities, electronic safes, hair dryers, complimentary WiFi, and furnished balconies or terraces with garden, pool, or ocean views. Star Prestige rooms provide enhanced experiences with exclusive lounge access offering premium beverages and snacks, superior room locations often beachfront or with ocean views, upgraded bathroom amenities including bathrobes and slippers, pillow menus, priority restaurant reservations, enhanced turndown service, and personalized attention. Family rooms offer additional space for families with children. The bright, cheerful design incorporates Caribbean colors, contemporary furnishings, and practical layouts creating comfortable tropical retreats suitable for families and couples seeking island paradise vacations."
    },
    {
      "resortName": "Pullman Cayo Coco",
      "location": "Cayo Coco, Morón, Ciego de Ávila, Cuba",
      "images": [
        "https://www.pullmanhotels.com/content/dam/pullman/cuba/cayo-coco/images/pullman-cayo-coco-resort.jpg",
        "https://www.pullmanhotels.com/content/dam/pullman/cuba/cayo-coco/images/pullman-cayo-coco-suite.jpg",
        "https://www.pullmanhotels.com/content/dam/pullman/cuba/cayo-coco/images/pullman-cayo-coco-pool.jpg",
        "https://www.pullmanhotels.com/content/dam/pullman/cuba/cayo-coco/images/pullman-cayo-coco-beach.jpg",
        "https://www.pullmanhotels.com/content/dam/pullman/cuba/cayo-coco/images/pullman-cayo-coco-restaurant.jpg"
      ],
      "resortDescription": "Pullman Cayo Coco is an upscale all-inclusive resort by AccorHotels on the stunning island of Cayo Coco, featuring direct access to pristine beaches and coral reef ecosystems. This modern property combines French hospitality standards with Caribbean island charm, offering sophisticated yet relaxed beachfront experiences. The resort features multiple specialty restaurants serving international and Cuban cuisines with gourmet presentations, stylish bars and lounges, several swimming pools including family and adults-only areas, comprehensive water sports center, diving facilities, fitness center with modern equipment, spa and wellness services, kids' club with organized activities, teen facilities, evening entertainment programs with live music and shows, sports facilities including tennis and beach volleyball, and attentive concierge services. The all-inclusive concept includes premium dining experiences, quality beverages, water sports, and entertainment. Cayo Coco's natural beauty includes pink flamingo colonies, protected beaches, and excellent diving sites, making it perfect for nature lovers and beach enthusiasts seeking upscale island retreats.",
      "roomDescription": "Pullman Cayo Coco offers contemporary rooms and suites with modern design emphasizing comfort and style. Accommodations feature comfortable king or double beds with quality linens, sleek modern furnishings with Caribbean touches, spacious bathrooms with walk-in showers or bathtubs, premium amenities, air conditioning, flat-screen TVs with international channels, stocked minibars, coffee/tea facilities, electronic safes, work desks in select categories, complimentary WiFi, and private balconies or terraces with views of tropical gardens, pools, or the ocean. Suites provide additional living space with separate seating areas, upgraded amenities, and enhanced services. The contemporary design uses clean lines, neutral palettes with blue accents, modern artwork, and quality materials creating sophisticated island atmospheres. Rooms balance functionality with relaxation, offering comfortable retreats after beach activities and island explorations."
    },
    {
      "resortName": "Meliá Cayo Coco",
      "location": "Cayo Coco, Morón, Ciego de Ávila, Cuba",
      "images": [
        "https://www.melia.com/content/dam/melia/cuba/cuba/cayo-coco/melia-cayo-coco/hotel/melia-cayo-coco-adults-only.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/cayo-coco/melia-cayo-coco/rooms/melia-cayo-coco-the-level-room.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/cayo-coco/melia-cayo-coco/hotel/melia-cayo-coco-pool.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/cayo-coco/melia-cayo-coco/hotel/melia-cayo-coco-beach.jpg",
        "https://www.melia.com/content/dam/melia/cuba/cuba/cayo-coco/melia-cayo-coco/restaurants/melia-cayo-coco-dining.jpg"
      ],
      "resortDescription": "Meliá Cayo Coco is an exclusive adults-only, all-inclusive luxury resort on Cayo Coco featuring stunning beachfront location with direct access to pristine white-sand beaches and protected coral reefs. This sophisticated property is designed exclusively for couples and adult travelers seeking tranquil, romantic Caribbean island experiences. The adults-only concept ensures peaceful atmospheres throughout all facilities. The resort features The Level service concept offering premium accommodations with exclusive amenities and personalized services, multiple gourmet specialty restaurants including Italian, Asian fusion, seafood, Cuban cuisine, and international buffets, elegant bars serving premium beverages and craft cocktails, multiple swimming pools including infinity pools with ocean views, adults-only beach areas with personalized service, YHI Spa offering comprehensive wellness treatments and hydrotherapy, modern fitness center, water sports including kayaking and sailing, diving center with PADI courses and reef excursions, tennis facilities, evening entertainment with live music and shows, and dedicated concierge services. The all-inclusive premium experience emphasizes quality dining, top-shelf spirits, romantic amenities, and sophisticated leisure activities perfect for honeymoons, anniversaries, and romantic getaways.",
      "roomDescription": "Meliá Cayo Coco offers spacious junior suites and suites designed exclusively for adults, featuring contemporary elegant design. All accommodations include king-size beds with luxury linens and pillow menus, sophisticated furnishings with romantic touches, modern bathrooms with hydromassage bathtubs and rainfall showers, premium bath amenities including bathrobes and slippers, individually controlled air conditioning, flat-screen satellite TVs, well-stocked minibars replenished daily, Nespresso coffee makers, electronic safes, complimentary WiFi, and private furnished terraces or balconies with ocean, garden, or pool views. The Level accommodations provide elevated luxury with exclusive access to The Level lounge offering gourmet breakfast, premium beverages, and snacks throughout the day, private pool and beach areas, butler service, priority restaurant reservations without time restrictions, upgraded minibar with premium spirits, enhanced bathroom products, welcome amenities, late checkout privileges, and highly personalized concierge attention. The sophisticated design emphasizes tranquility and romance with elegant color schemes, quality materials, intimate lighting, and thoughtful details creating perfect couples' sanctuaries."
    },
    {
      "resortName": "Gran Muthu Imperial",
      "location": "Cayo Guillermo, Morón, Ciego de Ávila, Cuba",
      "images": [
        "https://www.muthuhotels.com/content/dam/muthu/cuba/cayo-guillermo/gran-muthu-imperial/images/gran-muthu-resort-view.jpg",
        "https://www.muthuhotels.com/content/dam/muthu/cuba/cayo-guillermo/gran-muthu-imperial/images/gran-muthu-suite.jpg",
        "https://www.muthuhotels.com/content/dam/muthu/cuba/cayo-guillermo/gran-muthu-imperial/images/gran-muthu-pool-area.jpg",
        "https://www.muthuhotels.com/content/dam/muthu/cuba/cayo-guillermo/gran-muthu-imperial/images/gran-muthu-beach.jpg",
        "https://www.muthuhotels.com/content/dam/muthu/cuba/cayo-guillermo/gran-muthu-imperial/images/gran-muthu-restaurant.jpg"
      ],
      "resortDescription": "Gran Muthu Imperial is an adults-only, all-inclusive resort on Cayo Guillermo featuring beachfront location with direct access to spectacular white-sand beaches and turquoise Caribbean waters. This sophisticated property caters exclusively to couples and adult travelers seeking peaceful island retreats with comprehensive amenities. The adults-only environment creates tranquil, romantic atmospheres ideal for relaxation and romance. The resort features multiple specialty restaurants offering diverse international cuisines including Italian, Asian, seafood, and Cuban specialties, several bars serving premium beverages throughout the property, multiple swimming pools including infinity pools with ocean panoramas, private beach areas with loungers and shade structures, spa center offering therapeutic massages and beauty treatments, fitness facilities, water sports including snorkeling and kayaking, evening entertainment with live music and themed shows, sports facilities including beach volleyball and tennis, and personalized guest services. The all-inclusive concept includes unlimited dining at specialty restaurants, top-shelf spirits and cocktails, water sports activities, and entertainment programs. The island setting provides natural beauty, excellent beaches for swimming and sunbathing, and serene atmospheres perfect for disconnecting from daily stresses.",
      "roomDescription": "Gran Muthu Imperial features comfortable junior suites designed for adult guests, emphasizing relaxation and romantic comfort. All accommodations include king or queen beds with quality linens, contemporary tropical décor, bathrooms with showers and modern fixtures, bath amenities, air conditioning, flat-screen TVs with satellite channels, stocked minibars replenished daily with beverages and snacks, coffee/tea making facilities, electronic safes, hair dryers, complimentary WiFi, and furnished balconies or terraces offering garden, pool, or ocean views. Superior categories provide enhanced locations closer to beach or with better views, and upgraded amenities. The tropical design uses bright colors, comfortable furnishings, practical layouts, and Caribbean-inspired touches creating cheerful, relaxing spaces perfect for couples' vacations. Rooms offer comfortable retreats after beach days and island activities, with emphasis on simplicity and comfort rather than excessive luxury."
    },
    {
      "resortName": "Royalton Cayo Santa María",
      "location": "Cayo Santa María, Villa Clara, Cuba",
      "images": [
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/cayo-santa-maria/images/royalton-cayo-santa-maria-aerial.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/cayo-santa-maria/images/royalton-cayo-santa-maria-diamond-suite.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/cayo-santa-maria/images/royalton-cayo-santa-maria-pools.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/cayo-santa-maria/images/royalton-cayo-santa-maria-beach.jpg",
        "https://www.royaltonresorts.com/content/dam/royalton/cuba/cayo-santa-maria/images/royalton-cayo-santa-maria-restaurant.jpg"
      ],
      "resortDescription": "Royalton Cayo Santa María is a premium adults-only, all-inclusive luxury resort on the stunning island of Cayo Santa María, featuring direct access to pristine white-sand beaches and crystalline turquoise waters. This sophisticated modern property is designed exclusively for adults seeking upscale beachfront experiences in a tranquil island paradise. The resort offers Diamond Club premium accommodations with exclusive facilities and enhanced services, multiple specialty restaurants including Italian, Asian fusion, Brazilian steakhouse, seafood, Cuban cuisine, and international gourmet buffets, numerous bars and lounges serving unlimited premium beverages and cocktails, several swimming pools including stunning infinity pools with ocean views and private Diamond Club pool, private beach areas with Bali beds and butler service, Royal Spa featuring comprehensive wellness treatments and hydrotherapy circuits, state-of-the-art fitness center with modern equipment, extensive water sports including kayaking, snorkeling, and sailing, evening entertainment featuring live shows and music, casino, sports facilities including tennis and beach volleyball, and personalized concierge services. The all-inclusive experience includes 24-hour room service for suites, gourmet dining without reservations, top-shelf spirits, and romantic turndown service. The island location provides natural beauty with excellent beaches and coral reefs perfect for snorkeling.",
      "roomDescription": "Royalton Cayo Santa María features spacious luxury junior suites and suites exclusively for adults, with contemporary Caribbean design. All accommodations include king-size beds with luxury linens and pillow menus, elegant modern furnishings with sophisticated décor, marble bathrooms with whirlpool tubs and separate rainfall showers, premium bath amenities including bathrobes and slippers, individually controlled air conditioning, 55-inch flat-screen TVs with satellite channels, well-stocked minibars replenished daily with premium beverages and snacks, Lavazza coffee makers, electronic safes, hair dryers, irons with boards, complimentary high-speed WiFi, and furnished balconies or terraces with ocean, garden, or pool views. Diamond Club suites provide elevated luxury with exclusive access to Diamond Club lounge offering gourmet snacks and premium beverages throughout the day, private infinity pool and beach areas, butler service available 24/7, priority restaurant reservations, upgraded minibar selections with premium liquors, enhanced bathroom amenities and products, welcome sparkling wine and amenities, late checkout privileges, and highly personalized concierge services. The sophisticated design emphasizes romance and luxury with elegant color palettes, quality furn